version: '3.8'
services:
  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=apartment_management
      - PORT=4000
    depends_on:
      - mysql
    networks:
      - nest-network

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: apartment_management
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nest-network

volumes:
  mysql-data:
    driver: local

networks:
  nest-network:
    driver: bridge
