export enum AUTH_CONTANTS {
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILED = "LOGIN_FAILED",
    USER_EXISTS = "USER_EXISTS",
    USER_NOT_EXISTS = "USER_NOT_EXISTS",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    INVALID_TOKEN = "INVALID_TOKEN",
    MISSING_TOKEN = "MISSING_TOKEN",
    INVALID_USER = "INVALID_USER",
    REGISTER_SUCCESS = "REGISTER_SUCCESS",
    TOKEN_REFRESH_SUCCESS = "TOKEN_REFRESH_SUCCESS",
  }